import { useMemo, useState } from "react"
import { Check, ChevronRight, Clock3, Copy, CreditCard, FileCheck2, KeyRound, MessageCircle, Search, Send, ShieldAlert, UserRound, X } from "lucide-react"
import { reservations, type Reservation } from "../data/mock-data"

function Badge({ value }: { value: string }) {
  const kind = ["Pago", "Completa", "Ativo", "Respondido"].includes(value) ? "success" : ["Pendente", "Enviada", "Aguardando"].includes(value) ? "warning" : value === "Automático" ? "neutral" : "danger"
  return <span className={`status ${kind}`}><i />{value}</span>
}

export function OperationsScreen({ onOpenCommunication }: { onOpenCommunication: () => void }) {
  const [selected, setSelected] = useState<Reservation | null>(null)
  const [query, setQuery] = useState("")
  const [filter, setFilter] = useState("Todos")
  const filtered = useMemo(() => reservations.filter((item) => (filter === "Todos" || item.payment === filter || item.fnrh === filter) && `${item.guest} ${item.apartment} ${item.id}`.toLowerCase().includes(query.toLowerCase())), [query, filter])

  return <div className="screen operations-screen">
    <header className="page-heading"><div><span className="eyebrow">Hoje, 15 de março</span><h1>Painel operacional</h1><p>Acompanhe as chegadas e resolva pendências antes do check-in.</p></div><button className="button primary" onClick={onOpenCommunication}><MessageCircle /> Abrir comunicação</button></header>
    <section className="metrics-grid">
      <article className="metric-card featured"><span className="metric-icon"><UserRound /></span><div><strong>4</strong><p>Chegadas previstas</p></div><small>9 hóspedes</small></article>
      <article className="metric-card"><span className="metric-icon"><FileCheck2 /></span><div><strong>2</strong><p>FNRHs pendentes</p></div><small>Exigem atenção</small></article>
      <article className="metric-card"><span className="metric-icon"><KeyRound /></span><div><strong>2</strong><p>Acessos pendentes</p></div><small>Antes das 14h</small></article>
      <article className="metric-card"><span className="metric-icon"><MessageCircle /></span><div><strong>3</strong><p>Conversas abertas</p></div><small>2 não lidas</small></article>
    </section>
    <section className="operations-card">
      <header className="list-toolbar"><div><h2>Chegadas do dia</h2><p>{filtered.length} reservas encontradas</p></div><div className="toolbar-actions"><label className="search-box"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar hóspede, apto..." /></label><select value={filter} onChange={(e) => setFilter(e.target.value)} aria-label="Filtrar reservas"><option>Todos</option><option>Pago</option><option>Pendente</option><option>Completa</option></select></div></header>
      <div className="desktop-table"><table><thead><tr><th>Hóspede</th><th>Estadia</th><th>Pagamento</th><th>FNRH</th><th>Acesso</th><th>Comunicação</th><th><span className="sr-only">Abrir</span></th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} onClick={() => setSelected(item)}><td><div className="guest-cell"><span className="avatar">{item.initials}</span><div><strong>{item.guest}</strong><small>{item.id} · {item.guests} hóspedes</small></div></div></td><td><strong>Apto {item.apartment}</strong><small>{item.checkIn} · {item.time}</small></td><td><Badge value={item.payment} /></td><td><Badge value={item.fnrh} /></td><td><Badge value={item.access} /></td><td><Badge value={item.communication} /></td><td><ChevronRight /></td></tr>)}</tbody></table></div>
      <div className="mobile-cards">{filtered.map((item) => <button className="reservation-card" key={item.id} onClick={() => setSelected(item)}><div className="guest-cell"><span className="avatar">{item.initials}</span><div><strong>{item.guest}</strong><small>Apto {item.apartment} · {item.time}</small></div><ChevronRight /></div><div className="card-statuses"><Badge value={item.payment} /><Badge value={item.fnrh} /><Badge value={item.access} /></div></button>)}</div>
    </section>
    {selected && <><button className="drawer-backdrop" aria-label="Fechar detalhes" onClick={() => setSelected(null)} /><aside className="details-drawer" aria-label="Detalhes da reserva"><header><div><span className="eyebrow">{selected.id}</span><h2>Apartamento {selected.apartment}</h2></div><button className="icon-button" onClick={() => setSelected(null)} aria-label="Fechar"><X /></button></header><div className="drawer-scroll"><div className="guest-profile"><span className="avatar large">{selected.initials}</span><div><h3>{selected.guest}</h3><p>{selected.phone}</p><p>{selected.email}</p></div></div><div className="detail-grid"><div><span>Entrada</span><strong>{selected.checkIn}, {selected.time}</strong></div><div><span>Saída</span><strong>{selected.checkOut}, 11:00</strong></div><div><span>Hóspedes</span><strong>{selected.guests} pessoas</strong></div><div><span>Pagamento</span><Badge value={selected.payment} /></div></div><section className="access-card"><div><span><KeyRound /> Acesso TTLock</span><Badge value={selected.access} /></div><strong>{selected.password}</strong><p>Válida durante todo o período da hospedagem.</p>{selected.password !== "—" && <button className="button secondary small"><Copy /> Copiar senha</button>}</section><section className="drawer-section"><h3>Checklist da chegada</h3><div className="check-row"><span><Check /> Reserva confirmada</span><Badge value={selected.payment} /></div><div className="check-row"><span><FileCheck2 /> FNRH dos hóspedes</span><Badge value={selected.fnrh} /></div><div className="check-row"><span><KeyRound /> Credencial de acesso</span><Badge value={selected.access} /></div></section><section className="drawer-section"><h3>Observações</h3><p className="note">{selected.note}</p></section><section className="drawer-section"><h3>Histórico</h3><div className="timeline"><p><i /><span><strong>Reserva sincronizada</strong><small>Hoje, 08:42</small></span></p><p><i /><span><strong>Mensagem pré-check-in enviada</strong><small>Hoje, 09:05</small></span></p></div></section></div><footer><button className="button secondary"><Send /> Reenviar FNRH</button><button className="button primary"><KeyRound /> Liberar acesso</button><button className="button ghost full" onClick={onOpenCommunication}><MessageCircle /> Abrir conversa</button></footer></aside></>}
  </div>
}
